//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kdr.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CihazParca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CihazParca()
        {
            this.CihazTamirParca = new HashSet<CihazTamirParca>();
        }
    
        public int Id { get; set; }
        public string ParcaAdi { get; set; }
        public string Barkod { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> StokAdet { get; set; }
        public Nullable<decimal> MontajUcreti { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CihazTamirParca> CihazTamirParca { get; set; }
    }
}
