//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kdr.DBLayer
{
    using System;
    using System.Collections.Generic;

    public partial class CihazTamirParca : CihazParca
    {
        public int Id { get; set; }
        public int TamirTeslimId { get; set; }
        public int CihazParcaId { get; set; }
        public Nullable<int> EkleyenPersonel { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public Nullable<bool> ParcaBekliyor { get; set; }

        public virtual CihazParca CihazParca { get; set; }
        public virtual TamirTeslim TamirTeslim { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
