//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kdr.DBLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeknikProjeEntities : DbContext
    {
        public TeknikProjeEntities()
            : base("name=TeknikProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CihazParca> CihazParca { get; set; }
        public virtual DbSet<CihazTamirParca> CihazTamirParca { get; set; }
        public virtual DbSet<Il> Il { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<KargoFirma> KargoFirma { get; set; }
        public virtual DbSet<KargoSube> KargoSube { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<TamirDurum> TamirDurum { get; set; }
        public virtual DbSet<TamirTeslim> TamirTeslim { get; set; }
        public virtual DbSet<UygulamaMenu> UygulamaMenu { get; set; }
        public virtual DbSet<UygulamaMenuYetki> UygulamaMenuYetki { get; set; }
        public virtual DbSet<vTamirTeslim> vTamirTeslim { get; set; }
        public virtual DbSet<PersonelLoginSession> PersonelLoginSession { get; set; }
        public virtual DbSet<CihazKargoGonderim> CihazKargoGonderim { get; set; }
    }
}
