//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kdr.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TamirTeslim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TamirTeslim()
        {
            this.CihazTamirParca = new HashSet<CihazTamirParca>();
            this.CihazKargoGonderim = new HashSet<CihazKargoGonderim>();
        }
    
        public int Id { get; set; }
        public int MusteriId { get; set; }
        public int TeslimAlanPersonelId { get; set; }
        public Nullable<int> IadeEdenPersonelId { get; set; }
        public Nullable<int> TamirEdenPersonelId { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string SeriNo { get; set; }
        public string MusteriSorunAciklama { get; set; }
        public string TeknikPersonelAciklama { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<System.DateTime> IadeTarihi { get; set; }
        public string TeslimAlinanAksesuar { get; set; }
        public Nullable<decimal> TamirFiyat { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> KargoIleGeldi { get; set; }
        public Nullable<byte> TamirDurumId { get; set; }
        public Nullable<System.DateTime> TamirTarihi { get; set; }
        public Nullable<int> KontrolEdenPersonelId { get; set; }
        public Nullable<System.DateTime> KontrolTarihi { get; set; }
        public Nullable<bool> KargoIleGonderilecek { get; set; }
        public string TeslimAlan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CihazTamirParca> CihazTamirParca { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Personel Personel1 { get; set; }
        public virtual Personel Personel2 { get; set; }
        public virtual TamirDurum TamirDurum { get; set; }
        public virtual Personel Personel3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CihazKargoGonderim> CihazKargoGonderim { get; set; }

        public Musteri Musteri1
        {
            get => default;
            set
            {
            }
        }
    }
}
