//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kdr.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UygulamaMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UygulamaMenu()
        {
            this.UygulamaMenuYetki = new HashSet<UygulamaMenuYetki>();
        }
    
        public int Id { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> UstMenuId { get; set; }
        public string MenuClass { get; set; }
        public Nullable<int> IconIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UygulamaMenuYetki> UygulamaMenuYetki { get; set; }
    }
}
